version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: quiniela_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: quiniela_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=quiniela_pro
      - JWT_SECRET=CHANGE_ME_SUPER_SECRET
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - COOKIE_SECURE=false
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Chocodonut22
      - ADMIN_EMAIL=admin@local.com
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: quiniela_frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
